apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odd-collector.fullname" . }}
  labels:
    {{- include "odd-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.collectorConfig | nindent 4 }}
