apiVersion: v1
kind: Secret
metadata:
  name: odd-collector-base-secret
  labels:
    {{- include "odd-collector.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.passwordSecretsEnvs }}
  {{ $k | quote }}: {{ $v | toString | b64enc | quote }}
  {{- end }}